apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 5m0s
  timeout: 3m0s
  chart:
    spec:
      chart: speedtest-prometheus
      version: ">=2.2.1"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  targetNamespace: monitoring
  values:
    #affinity:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: node-role.kubernetes.io/monitoring
    #          operator: In
    #          values:
    #          - "true"
    serviceMonitor:
      enabled: true
