---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: automation
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 1.3.5-12

    env:
      TZ: Europe/Vienna
      FLOWS: flows.json
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
      hosts:
        - host: node-red.k8s.home
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: k8s-home-cert
          hosts:
            - node-red.k8s.home

    persistence:
      data:
        enabled: true
        mountPath: /data
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: 5Gi

    nodeSelector:
      kubernetes.io/arch: amd64
      # node-role.kubernetes.io/application: "true"

    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
        cpu: 1000m
