apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      version: '>=4.0.10'
  interval: 5m0s
  releaseName: nfs-subdir-external-provisioner
  targetNamespace: kube-system
  values:
    replicaCount: 1
    strategyType: Recreate

    nfs:
      server: nas.home
      path: /volume1/k3s-volumes
      mountOptions:

    storageClass:
      create: true
      # provisionerName: k3s.home/nfs-subdir-external-provisioner
      defaultClass: false
      name: nfs-client
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      archiveOnDelete: true
      # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
      accessModes: ReadWriteOnce

    leaderElection:
      # When set to false leader election will be disabled
      enabled: true

    rbac:
      create: true

    # If true, create & use Pod Security Policy resources
    # https://kubernetes.io/docs/concepts/policy/pod-security-policy/
    podSecurityPolicy:
      enabled: false

    serviceAccount:
      create: true

    nodeSelector:
      kubernetes.io/arch: amd64
