{
 "title": "Speedtest Dashboard",
 "description": "A dashboard for Prometheus Speedtest Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Download Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Ping Latency Timeline",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Ping Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Ping"
    }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  {
   "title": "Current Ping Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Ping Latency"
    }
   ]
  },
  {
   "title": "Speedtest Timeline",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps", "label": "Speed Mbps" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "Download Speed"
    },
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "Upload Speed"
    }
   ]
  }
 ]
}