apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: speedtest-exporter
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    #affinity:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: node-role.kubernetes.io/monitoring
    #          operator: In
    #          values:
    #          - "true"
    prometheus:
      podMonitor:
        enabled: true
        interval: 15m
