---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 5m0s
  timeout: 3m0s
  chart:
    spec:
      chart: speedtest-exporter
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    #affinity:
    #  nodeAffinity:
    #    requiredDuringSchedulingIgnoredDuringExecution:
    #      nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: node-role.kubernetes.io/monitoring
    #          operator: In
    #          values:
    #          - "true"
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.2.1
    tolerations:
    - key: "arm"
      operator: "Exists"
    prometheus:
      podMonitor:
        enabled: true
        interval: 30m
        scrapeTimeout: 5m
        additionalLabels: {}
